name: Test build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['14', '16', '18', '19']
        webpack-version: ['4', '5']
        include:
          - webpack-version: 5
            webpack-cli-version: 5
            # https://github.com/YashdalfTheGray/auto-ngtemplate-loader/issues/279
            auto-ngtemplate-loader-version: 3.1.2
            babel-loader-version: 9
            html-loader-version: 4
          - webpack-version: 4
            webpack-cli-version: 3
            # https://github.com/YashdalfTheGray/auto-ngtemplate-loader/issues/279
            auto-ngtemplate-loader-version: 3.1.1
            babel-loader-version: 8
            html-loader-version: 1

    env:
      WEBPACK_VERSION: ${{ matrix.webpack-version }}
      WEBPACK_CLI_VERSION: ${{ matrix.webpack-cli-version }}
      LOADER_UTILS_VERSION: ${{ matrix.loader-utils-version }}
      AUTO_NGTEMPLATE_LOADER_VERSION: ${{ matrix.auto-ngtemplate-loader-version }}
      BABEL_LOADER_VERSION: ${{ matrix.babel-loader-version }}
      HTML_LOADER_VERSION: ${{ matrix.html-loader-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node modules
        run: npm ci

      - name: Install webpack specific dependencies
        run: npm install webpack@$WEBPACK_VERSION webpack-cli@$WEBPACK_CLI_VERSION auto-ngtemplate-loader@$LOADER_UTILS_VERSION babel-loader@$BABEL_LOADER_VERSION html-loader@$HTML_LOADER_VERSION

      - name: Test Webpack build
        run: |
          npm test
        if: matrix.node != 19 || matrix.webpack-version != '4' || matrix.os != 'windows-latest'

      - name: Test Webpack build (Node.js v19 and Webpack v4)
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm test
        if: matrix.node == 19 && matrix.webpack-version == '4' && matrix.os != 'windows-latest'
        # https://github.com/webpack/webpack/issues/14532 🙄

      - name: Test Webpack build (Node.js v19, Webpack v4, and Windows)
        run: |
          $Env:NODE_OPTIONS = "--openssl-legacy-provider"
          npm test
        if: matrix.node == 19 && matrix.webpack-version == '4' && matrix.os == 'windows-latest'
        # https://github.com/webpack/webpack/issues/14532 🙄

      - name: Upload the bundle
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('bundle-{0}-{1}.js', matrix.node-version, runner.os) }}
          path: public/bundle.js
