name: Test build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node modules
        run: npm ci

      - name: Test Webpack build
        run: npm test

      - name: Upload the bundle
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('bundle-{0}-{1}.js', matrix.node-version, runner.os) }}
          path: output/bundle.js
