name: Test build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['14', '16', '18', '19']
        webpack-version: ['4', '5']
      include:
        - webpack-version: 5
          webpack-cli-version: 4
        - webpack-version: 4
          webpack-cli-version: 3

    env:
      WEBPACK_VERSION: ${{ matrix.webpack-version }}
      WEBPACK_CLI_VERSION: ${{ matrix.webpack-cli-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node modules
        run: npm ci

      - name: Install webpack specific dependencies
        run: npm install webpack@$WEBPACK_VERSION webpack-cli@$WEBPACK_CLI_VERSION

      - name: Install Webpack v5
        run: npm install webpack@5 webpack-cli@4
        if: matrix.webpack-version == '5'

      - name: Test Webpack build
        run: npm test

      - name: Upload the bundle
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ format('bundle-{0}-{1}.js', matrix.node-version, runner.os) }}
          path: public/bundle.js
